name: PR Pipeline

on:
  pull_request:
    branches:
      - develop
      
jobs:
  static-code-analysis:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Finds anti-patterns in code
        run: |
          echo "Run Pylint"
      - name: Run security checks
        run: |
          echo "Run Bandit"